version: "2"

networks:
  default:
    name: local-stack

services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    container_name: dnsmasq
#    environment:
#      - HTTP_USER=foo
#      - HTTP_PASS=bar
    restart: always
    volumes:
      - dns_conf:/etc/
    ports:
      - "53:53/udp"
      - "5380:8080"

volumes:
  dns_conf:
    external: true
