version: "2"

networks:
  default:
    name: local-stack

services:
  drone-server:
    image: drone/drone:latest
    container_name: drone-server
    ports:
      - 8000:80
      - 9010:443
    volumes:
      - drone_data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_GITEA_SERVER=localhost:3000
#      - DRONE_GITEA_CLIENT_ID=<OAuth2_ID>
#      - DRONE_GITEA_CLIENT_SECRET=<OAuth2_SECRET_KEY>
#      - DRONE_RPC_SECRET=<DRONE-RUNNER_SECRET_KEY>
      - DRONE_SERVER_HOST=localhost:8000
      - DRONE_SERVER_PROTO=http

  drone-runner:
    image: drone/drone-runner-docker:latest
    container_name: drone-server
    ports:
      - "3002:3000"
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=<DRONE-RUNNER_SECRET_KEY>
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME="drone-runner"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  drone_data:
    external: true
      