version: '2'

networks:
  default:
    name: local-stack

services:
  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud:latest
    restart: always
    links:
      - nextcloud-db
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cubicmouse.asuscomm.com`) && PathPrefix(`/nextcloud/`)"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.nextcloud.middlewares=nextcloudstrip"
      - "traefik.http.middlewares.nextcloudstrip.stripprefix.prefixes=/nextcloud"
  
  cron:
    container_name: nextcloud-app-cron
    image: rcdailey/nextcloud-cronjob
    restart: always
    depends_on:
    - nextcloud-app
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - NEXTCLOUD_CONTAINER_NAME=nextcloud-app

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

volumes:
  nextcloud_data:
    external: true
  nextcloud_db:
    external: true
  document_data:
    external: true
  document_log:
    external: true
