version: '2'

networks:
  default:
    name: local-stack

services:
  starter:
    container_name: starter
    image: httpd:alpine
    restart: always
    volumes:
      - starter_html:/usr/local/apache2/htdocs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.starter.entrypoints=websecure"
      - "traefik.http.routers.starter.rule=Host(`cubicmouse.asuscomm.com`)"
      - "traefik.http.routers.starter.service=starter"
      - "traefik.http.services.starter.loadbalancer.server.port=80"
      - "traefik.http.routers.starter.tls=true"
      - "traefik.http.routers.starter.tls.certresolver=letsEncrypt"
      
volumes:
  starter_html:
    external: true
